### ISSUE TITLE
[BUG] <a> links are not replaced with replacementPatterns

### ISSUE THREAD

**Issue by niosus** [UmbrellaDocs/linkspector#116]
**Describe the bug**
I have a link in my document that looks like this: `<a href="https://youtu.be/blah"></a>`

I want to replace it with a link that produces a 404:

```yaml
replacementPatterns:
  - pattern: "<a href=\"https://youtu.be/blah\"></a>"
    replacement: "[blah](https://blah.blah)"
```

When I run the linkspector, my file passes the inspection.

**Expected behavior**
I expect the original link to be replaced with the broken one and the inspection to fail.
