### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by AlexMRuch** [UmbrellaDocs/linkspector#126]
I'm trying to have linkspector ignore all urls that reference localhost, but I keep getting this error:
```
reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): unexpected token
```

Here's my `.linkspector.yml` file, which I based on the example you all give [here](https://github.com/UmbrellaDocs/linkspector?tab=readme-ov-file#sample-configuration):
```
ignorePatterns:
  - pattern: '^https://localhost*$'
useGitIgnore: true
```

**Comment by gaurav-nelson** [comment]
The issue is that you must specify either 'files' or 'dirs' in your config. PS: https://github.com/UmbrellaDocs/linkspector?tab=readme-ov-file#default-configuration

**Comment by rmarting** [comment]
Just in case, this configuration works perfectly to skip any localhost reference:

```yaml
aliveStatusCodes:
  - 200
  - 201
  - 204
  - 406
  - 429
dirs:
  - ./
  - docs/
  - src/
  - static/
excludedDirs:
  - .github/
excludedFiles:
  - LICENSE
  - docusaurus.config.js
ignorePatterns:
  - pattern: '^http://localhost.*$'
useGitIgnore: true
```

Note that it is using `http` instead of `https`. But it depends of your local environment.
