### ISSUE TITLE
[BUG] Patterns in `README.md` need to escape the `.` character

### ISSUE THREAD

**Issue by dagardner-nv** [UmbrellaDocs/linkspector#129]
**Describe the bug**
I'm not 100% sure, but in the documentation for the `ignorePatterns` and `replacementPatterns` config sections, the `.` characters need to be escaped in order to match the dot in the domain name and not be treated as a regex wild-card.

I suspect:
```yaml
ignorePatterns:
  - pattern: '^https://example.com/skip/.*$'
  - pattern: "^(ftp)://[^\\s/$?#]*\\.[^\\s]*$"
```

Should be:
```yaml
ignorePatterns:
  - pattern: '^https://example\\.com/skip/.*$'
  - pattern: "^(ftp)://[^\\s/$?#]*\\.[^\\s]*$"
```

Sorry if this is reported in error.

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
n/a

**Additional context**
n/a
