### ISSUE TITLE
[FEATURE REQ]  Be able to scan Github wiki page repo

### ISSUE THREAD

**Issue by kaktusztea** [UmbrellaDocs/linkspector#68]
Hi,

I have a Github repo and I'd like to check its wiki page repo for broken links as well.
https://github.com/kaktusztea/km100/wiki

Created a workflow for it:
https://github.com/kaktusztea/km100/blob/master/.github/workflows/markdown_links_wiki.yml

But it fails and I don't know why.
https://github.com/kaktusztea/km100/actions/runs/9646569412

```
Run umbrelladocs/action-linkspector@v1
Run reviewdog/action-setup@v1
Run set -eu
🐶 Installing reviewdog ... https://github.com/reviewdog/reviewdog
Run set -eu
📖 reviewdog -h
Run $GITHUB_ACTION_PATH/script.sh
🔗💀 Installing linkspector ... https://github.com/UmbrellaDocs/linkspector
 Running linkspector with reviewdog 🐶 ...
  reviewdog: failed to unmarshal rdjson (DiagnosticResult): proto: unexpected EOF
  Error: Process completed with exit code 1.
```

Additionally on wiki page you don't use link like "Something.md", but only as "Something" that points to the selected page.

**Comment by kaktusztea** [comment]
It should have an [enhancement](https://github.com/UmbrellaDocs/linkspector/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) label instead of "bug", but I can not change it.

**Comment by kaktusztea** [comment]
I was able to do this by using replacementPatterns:

```
dirs:
  - .

replacementPatterns:
  # Handle links with anchors: filename#anchor -> filename.md#anchor
  - pattern: '^([A-Za-z0-9._-]+)(#.+)$'
    replacement: '$1.md$2'
  # Handle links without anchors: filename -> filename.md
  - pattern: '^([A-Za-z0-9._-]+)$'
    replacement: '$1.md'
```
