### ISSUE TITLE
[BUG] Reddit links result in 403 when run in Github Actions

### ISSUE THREAD

**Issue by yogan** [UmbrellaDocs/linkspector#76]
**Describe the bug**
Checking locally works find, but running in Github Actions leads to a 403.

**To Reproduce**
Example `README.md`:
```
Redditor [u/Boojum](https://old.reddit.com/user/Boojum) has crafted a nice 
[surprise input](https://old.reddit.com/r/adventofcode/comments/18firip/2023_day_10_an_alternate_input_to_visualize/).
```

I thought it might have to do with `old.reddit.com`, but this rewrite rule in `.linkspector.yml` did not help:

```yml
replacementPatterns:
  - pattern: "https?://old.reddit.com"
    replacement: 'https://www.reddit.com'
```

I'm not sure how I can get more details (e.g. headers) to see what is different locally and in GitHub Actions. I'll gladly provide more details if I can get some hints on how to get them.
